# Managed by scripts/standardize-metadata.py
autoDiscovery:
  clusterName: goldenpath-dev-eks-31-12-25-04
awsRegion: eu-west-2
rbac:
  serviceAccount:
    create: false
    name: cluster-autoscaler
    annotations: {}
extraArgs:
  balance-similar-node-groups: 'true'
  skip-nodes-with-local-storage: 'false'
  expander: least-waste
governance:
  id: HELM_CLUSTER_AUTOSCALER
  owner: platform-team
  risk_profile:
    production_impact: low
    security_risk: none
    coupling_risk: low
  reliability:
    rollback_strategy: git-revert
    observability_tier: bronze
