{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: backstage-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.secrets.postgresPassword.remoteRef.key }}
        property: {{ .Values.externalSecret.secrets.postgresPassword.remoteRef.property }}
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.externalSecret.secrets.postgresUser.remoteRef.key }}
        property: {{ .Values.externalSecret.secrets.postgresUser.remoteRef.property }}
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.secrets.githubToken.remoteRef.key }}
        property: {{ .Values.externalSecret.secrets.githubToken.remoteRef.property }}
{{- end }}
