apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.10.0
      helm:
        valueFiles:
          - $values/gitops/helm/ingress-nginx/values/dev.yaml
    - repoURL: https://github.com/mikeybeezy/goldenpath-idp-infra.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
