apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  releaseName: keycloak
  chart:
    spec:
      chart: keycloak
      version: "15.2.8"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m
  values:
    auth:
      adminUser: admin
      adminPassword: "${KEYCLOAK_ADMIN_PASSWORD:=changeme}"
    proxyAddressForwarding: true
