apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

images:
  - name: ${{ values.component_id }}
    newName: 593517239005.dkr.ecr.eu-west-2.amazonaws.com/${{ values.component_id }}
    # Tag managed by Argo CD Image Updater
    newTag: latest

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ecr-pull-secret
    target:
      kind: Deployment
      name: ${{ values.component_id }}
  # Dev: minimal replicas (or user defined)
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: ${{ values.replicas }}
    target:
      kind: Deployment
      name: ${{ values.component_id }}

configMapGenerator:
  - name: ${{ values.component_id }}-config
    literals:
      - APP_ENV=${{ values.environment }}
      - LOG_LEVEL=debug
