site_name: Golden Path IDP - Infrastructure
nav:
  - Overview: README.md
  - Foundations:
      - docindex: docs/90-doc-system/00_DOC_INDEX.md
  - Architecture:
      - ADR Index: docs/adrs/README.md
      - Recent ADRs: docs/30-architecture/
  - Delivery:
      - Overview: docs/40-delivery/
  - Governance:
      - Health Dashboard: PLATFORM_HEALTH.md
      - Index: docs/10-governance/
      - Emoji Policy: docs/10-governance/EMOJI_POLICY.md
  - Operations:
      - Runbooks: docs/70-operations/runbooks/
  - Changelog:
      - Index: docs/changelog/README.md
plugins:
  - techdocs-core
# Trigger Rebuild Thu Jan  8 06:50:03 GMT 2026
