# Managed by scripts/standardize_metadata.py
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Values.appName }}-efs'
  namespace: '{{ .Values.namespace }}'
  labels:
    app.kubernetes.io/name: '{{ .Values.appName }}'
    app.kubernetes.io/instance: '{{ .Values.appName }}'
  annotations:
    goldenpath.idp/id: APPS_TEMPLATES_METADATA
    goldenpath.idp/owner: None
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: '{{ .Values.efsStorageClassName }}'
  resources:
    requests:
      storage: '{{ .Values.efsStorageSize }}'
