apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.appName }}-data"
  namespace: "{{ .Values.namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Values.appName }}"
    app.kubernetes.io/instance: "{{ .Values.appName }}"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ .Values.storageClassName }}"
  resources:
    requests:
      storage: "{{ .Values.storageSize }}"
