apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "stateful-app-efs"
  namespace: "apps-stateful"
  labels:
    app.kubernetes.io/name: "stateful-app"
    app.kubernetes.io/instance: "stateful-app"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "efs-sc"
  resources:
    requests:
      storage: "20Gi"
