# Managed by scripts/standardize_metadata.py
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stateful-app-data
  namespace: apps-stateful
  labels:
    app.kubernetes.io/name: stateful-app
    app.kubernetes.io/instance: stateful-app
  annotations:
    goldenpath.idp/id: APPS_BASE_METADATA
    goldenpath.idp/owner: None
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
