# Managed by scripts/standardize_metadata.py
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stateful-app-reader
  namespace: apps-stateful
  annotations:
    goldenpath.idp/id: APPS_BASE_METADATA
    goldenpath.idp/owner: None
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stateful-app-reader
  namespace: apps-stateful
  annotations:
    goldenpath.idp/id: APPS_BASE_METADATA
    goldenpath.idp/owner: None
subjects:
  - kind: ServiceAccount
    name: stateful-app
    namespace: apps-stateful
roleRef:
  kind: Role
  name: stateful-app-reader
  apiGroup: rbac.authorization.k8s.io
