apiVersion: v1
kind: Service
metadata:
  name: stateful-app
  namespace: apps-stateful
  labels:
    app.kubernetes.io/name: stateful-app
    app.kubernetes.io/instance: stateful-app
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: stateful-app
  ports:
    - name: http
      port: 80
      targetPort: http
