# Managed by scripts/standardize_metadata.py
apiVersion: v1
kind: Service
metadata:
  name: stateful-app
  namespace: apps-stateful
  labels:
    app.kubernetes.io/name: stateful-app
    app.kubernetes.io/instance: stateful-app
  annotations:
    goldenpath.idp/id: APPS_BASE_METADATA
    goldenpath.idp/owner: None
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: stateful-app
  ports:
    - name: http
      port: 80
      targetPort: http
