apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "stateful-app"
  namespace: "apps-stateful"
  labels:
    app.kubernetes.io/name: "stateful-app"
    app.kubernetes.io/instance: "stateful-app"
    app.kubernetes.io/managed-by: "argocd"
    app.kubernetes.io/version: "1.0.0"
    platform.goldenpath.dev/team: "platform"
    platform.goldenpath.dev/env: "dev"
    platform.goldenpath.dev/build-id: "dev-0000"
spec:
  serviceName: "stateful-app"
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: "stateful-app"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "stateful-app"
        app.kubernetes.io/instance: "stateful-app"
        app.kubernetes.io/version: "1.0.0"
        platform.goldenpath.dev/team: "platform"
        platform.goldenpath.dev/env: "dev"
        platform.goldenpath.dev/build-id: "dev-0000"
    spec:
      serviceAccountName: "stateful-app"
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: "stateful-app"
          image: "nginx:1.27"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          env:
            - name: ENV
              value: "dev"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "gp3"
        resources:
          requests:
            storage: "10Gi"
