apiVersion: v1
kind: Service
metadata:
  name: ${{ values.component_id }}
  labels:
    app: ${{ values.component_id }}
    app.kubernetes.io/name: ${{ values.component_id }}
spec:
  ports:
    - port: 80
      targetPort: http
      name: http
  clusterIP: None # Headless
  selector:
    app: ${{ values.component_id }}
