# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/crds/application-crd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-prometheus
  namespace: argocd
spec:
  project: default
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 25.8.0
      helm:
        valueFiles:
          - $values/gitops/helm/prometheus/values/staging.yaml
    - repoURL: https://github.com/mikeybeezy/goldenpath-idp-infra.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
