apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    goldenpath.idp/id: SEC-0007
    platform.idp/service: payments
  name: payments-payments-db-credentials-sync
  namespace: payments
spec:
  dataFrom:
  - extract:
      key: goldenpath/dev/payments/payments-db-credentials
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    creationPolicy: Owner
    name: payments-db-creds
