# Managed by scripts/standardize_metadata.py
appName: wordpress-efs
namespace: apps-wordpress-efs
appVersion: 6.5.2
team: platform
env: dev
buildId: dev-0000
replicas: 2
serviceAccountName: wordpress-efs
appImage: wordpress:6.5.2-apache
appPort: 80
servicePort: 80
cpuRequest: 100m
cpuLimit: 500m
memoryRequest: 256Mi
memoryLimit: 512Mi
appHost: wordpress.dev.goldenpath.local
kongAuthPlugin: sample-auth
kongRateLimitPlugin: sample-rate-limit
storageClassName: gp3
storageSize: 10Gi
quotaRequestsCpu: '1'
quotaRequestsMemory: 1Gi
quotaLimitsCpu: '2'
quotaLimitsMemory: 2Gi
quotaRequestsStorage: 50Gi
efsStorageClassName: efs-sc
efsFileSystemId: fs-12345678
efsStorageSize: 50Gi
governance:
  id: APPS_HELM_METADATA
  owner: platform-team
  risk_profile: null
  reliability: null
