apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kong
  namespace: kong-system
spec:
  releaseName: kong
  chart:
    spec:
      chart: kong
      version: "2.36.0"
      sourceRef:
        kind: HelmRepository
        name: konghq
        namespace: flux-system
  interval: 5m
  values:
    ingressController:
      enabled: true
      installCRDs: true
    proxy:
      type: LoadBalancer
    env:
      database: "off"
