# Managed by scripts/standardize_metadata.py
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-wordpress-efs
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - service.yaml
  - statefulset.yaml
  - pvc.yaml
  - pvc-efs.yaml
  - resourcequota.yaml
  - storageclass-efs.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - networkpolicy.yaml
  - dashboards/configmap-dashboard.yaml
metadata:
  annotations:
    goldenpath.idp/id: APPS_BASE_METADATA
    goldenpath.idp/owner: None
