# Managed by scripts/standardize_metadata.py
apiVersion: v1
kind: Namespace
metadata:
  name: apps-wordpress-efs
  labels:
    kubernetes.io/metadata.name: apps-wordpress-efs
  annotations:
    goldenpath.idp/id: APPS_BASE_METADATA
    goldenpath.idp/owner: None
