apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "wordpress-efs-data"
  namespace: "apps-wordpress-efs"
  labels:
    app.kubernetes.io/name: "wordpress-efs"
    app.kubernetes.io/instance: "wordpress-efs"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp3"
  resources:
    requests:
      storage: "10Gi"
