# Managed by scripts/standardize_metadata.py
apiVersion: v1
kind: Service
metadata:
  name: wordpress-efs
  namespace: apps-wordpress-efs
  labels:
    app.kubernetes.io/name: wordpress-efs
    app.kubernetes.io/instance: wordpress-efs
  annotations:
    goldenpath.idp/id: APPS_BASE_METADATA
    goldenpath.idp/owner: None
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: wordpress-efs
  ports:
    - name: http
      port: 80
      targetPort: http
