# Managed by scripts/standardize_metadata.py
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress-efs
  namespace: apps-wordpress-efs
  annotations:
    goldenpath.idp/id: APPS_BASE_METADATA
    goldenpath.idp/owner: None
