apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: governance-config-driven-metadata
  title: CONFIG_DRIVEN_METADATA
  description: This document defines the strategy for **Config-Driven Metadata Governance**.
    Historically, platform rules (standardization and validation) were hardcoded in
    Python scripts. This strategy moves those ...
  annotations:
    github.com/project-slug: mikeybeezy/goldenpath-idp-infra
    backstage.io/view-url: https://github.com/mikeybeezy/goldenpath-idp-infra/blob/main/docs/10-governance/CONFIG_DRIVEN_METADATA.md
    backstage.io/edit-url: https://github.com/mikeybeezy/goldenpath-idp-infra/edit/main/docs/10-governance/CONFIG_DRIVEN_METADATA.md
  tags:
    - gove
    - governance
    - documentation
    - policy
  links:
    - url: https://github.com/mikeybeezy/goldenpath-idp-infra/blob/main/docs/10-governance/CONFIG_DRIVEN_METADATA.md
      title: View on GitHub
      icon: github
spec:
  type: documentation
  lifecycle: active
  owner: platform-team
  subcomponentOf: governance-documentation
