# Managed by scripts/standardize_metadata.py
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.appName }}'
  namespace: '{{ .Values.namespace }}'
  labels:
    app.kubernetes.io/name: '{{ .Values.appName }}'
    app.kubernetes.io/instance: '{{ .Values.appName }}'
  annotations:
    goldenpath.idp/id: APPS_TEMPLATES_METADATA
    goldenpath.idp/owner: None
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: '{{ .Values.appName }}'
  ports:
    - name: http
      port: '{{ .Values.servicePort }}'
      targetPort: http
