apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Values.appName }}"
    app.kubernetes.io/instance: "{{ .Values.appName }}"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "{{ .Values.appName }}"
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: http
