apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: <app>
 namespace: <app>
 annotations:
   konghq.com/strip-path: "false"
  #  konghq.com/plugins: grade-demo-auth-plugin, grade-demo-ratelimit   # Plugin names referenced in KongPlugin resources
   kubernetes.io/ingress.class: kong
   konghq.com/methods: "GET, POST"
spec:
 ingressClassName: kong
 rules:
   - http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: app # Name of your K8s Service
               port:
                 number: 3000    # Port exposed by your Service
