apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.appName }}-efs"
  namespace: "{{ .Values.namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Values.appName }}"
    app.kubernetes.io/instance: "{{ .Values.appName }}"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "{{ .Values.efsStorageClassName }}"
  resources:
    requests:
      storage: "{{ .Values.efsStorageSize }}"
