apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Values.appName }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/name: "{{ .Values.appName }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Values.appName }}"
  namespaceSelector:
    matchNames:
      - "{{ .Values.namespace }}"
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
