# Managed by scripts/standardize_metadata.py
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.serviceAccountName }}'
  namespace: '{{ .Values.namespace }}'
  annotations:
    goldenpath.idp/id: APPS_TEMPLATES_METADATA
    goldenpath.idp/owner: None
