# Managed by scripts/standardize_metadata.py
appConfig:
  catalog:
    locations:
      - type: url
        target: https://raw.githubusercontent.com/mikeybeezy/goldenpath-idp-infra/governance-registry/backstage-catalog/templates/ci-apply-dev/template.yaml
        rules:
          - allow:
              - Template
      - type: url
        target: https://raw.githubusercontent.com/mikeybeezy/goldenpath-idp-infra/governance-registry/backstage-catalog/templates/app-template/template.yaml
        rules:
          - allow:
              - Template
governance:
  id: HELM_BACKSTAGE_METADATA
  owner: null
  risk_profile: null
  reliability: null
