apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service-headless.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: goldenpath-idp

images:
  - name: hello-goldenpath-idp
    newName: ${{ values.component_id }}
    newTag: latest
