apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${{ values.component_id }}-db-creds
  labels:
    app: ${{ values.component_id }}
    app.kubernetes.io/name: ${{ values.component_id }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ${{ values.component_id }}-db-creds
    creationPolicy: Owner
  data:
    # Maps AWS Secret Keys to K8s Secret Keys
    - secretKey: DB_HOST
      remoteRef:
        key: goldenpath/${{ values.environment }}/${{ values.databaseName }}/postgres
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: goldenpath/${{ values.environment }}/${{ values.databaseName }}/postgres
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: goldenpath/${{ values.environment }}/${{ values.databaseName }}/postgres
        property: dbname
    - secretKey: DB_USER
      remoteRef:
        key: goldenpath/${{ values.environment }}/${{ values.databaseName }}/postgres
        property: username
    - secretKey: DB_PASS
      remoteRef:
        key: goldenpath/${{ values.environment }}/${{ values.databaseName }}/postgres
        property: password
