apiVersion: v1
kind: Service
metadata:
  name: "<APP_NAME>"
  namespace: "<NAMESPACE>"
  labels:
    app.kubernetes.io/name: "<APP_NAME>"
    app.kubernetes.io/instance: "<APP_NAME>"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "<APP_NAME>"
  ports:
    - name: http
      port: <SERVICE_PORT>
      targetPort: http
