apiVersion: v1
kind: Service
metadata:
  name: "{{ values.app_name }}"
  namespace: "{{ values.namespace }}"
  labels:
    app.kubernetes.io/name: "{{ values.app_name }}"
    app.kubernetes.io/instance: "{{ values.app_name }}"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "{{ values.app_name }}"
  ports:
    - name: http
      port: {{ values.service_port }}
      targetPort: http
