# Managed by scripts/standardize_metadata.py
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-stateless-app
  namespace: apps-sample-stateless
  annotations:
    goldenpath.idp/id: APPS_BASE_METADATA
    goldenpath.idp/owner: None
