name: GitHub AWS OIDC
####
on:
  push:
    branches:
      - superlint

permissions:
  id-token: write
  contents: read

TF_AWS_IAM_ROLE_DEV = both scoped to just dev
 region = eu-west-2
 DynamoDB lock table name = goldenpath-idp-dev-db-key

  Repo secret and Repo variable s TF_AWS_IAM_ROLE, scopped to dev test and staging,  s3 bucket goldenpath-idp-dev-bucket
jobs:
  oidc-test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
      - name: Test AWS credentials
        run: aws sts get-caller-identity
